"""admin dashboard phase 1

Revision ID: 1595e0843e18
Revises: 8b6f694fc2c3
Create Date: 2026-04-06 22:25:18.852442
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pathlib import Path
from dotenv import load_dotenv
# Load .env relative to the project root (alembic.ini's parent).
# In flexloop-server layout: alembic/versions/<hash>.py -> parents[2] is flexloop-server/
load_dotenv(Path(__file__).resolve().parents[2] / ".env")

revision: str = '1595e0843e18'
down_revision: Union[str, None] = '8b6f694fc2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_provider', sa.String(length=32), nullable=False),
    sa.Column('ai_model', sa.String(length=128), nullable=False),
    sa.Column('ai_api_key', sa.String(length=256), nullable=False),
    sa.Column('ai_base_url', sa.String(length=256), nullable=False),
    sa.Column('ai_temperature', sa.Float(), nullable=False),
    sa.Column('ai_max_tokens', sa.Integer(), nullable=False),
    sa.Column('ai_review_frequency', sa.String(length=32), nullable=False),
    sa.Column('ai_review_block_weeks', sa.Integer(), nullable=False),
    sa.Column('admin_allowed_origins', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_pricing',
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('input_per_million', sa.Float(), nullable=False),
    sa.Column('output_per_million', sa.Float(), nullable=False),
    sa.Column('cache_read_per_million', sa.Float(), nullable=True),
    sa.Column('cache_write_per_million', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('model_name')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_timestamp'), 'admin_audit_log', ['timestamp'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_expires_at'), 'admin_sessions', ['expires_at'], unique=False)

    # Seed the single app_settings row from current .env defaults.
    # This runs once per deployment; subsequent changes happen via the admin UI.
    from sqlalchemy import table, column, String, Integer, Float, JSON
    import os

    app_settings_table = table(
        "app_settings",
        column("id", Integer),
        column("ai_provider", String),
        column("ai_model", String),
        column("ai_api_key", String),
        column("ai_base_url", String),
        column("ai_temperature", Float),
        column("ai_max_tokens", Integer),
        column("ai_review_frequency", String),
        column("ai_review_block_weeks", Integer),
        column("admin_allowed_origins", JSON),
    )

    op.bulk_insert(
        app_settings_table,
        [{
            "id": 1,
            "ai_provider": os.environ.get("AI_PROVIDER", "openai"),
            "ai_model": os.environ.get("AI_MODEL", "gpt-4o-mini"),
            "ai_api_key": os.environ.get("AI_API_KEY", ""),
            "ai_base_url": os.environ.get("AI_BASE_URL", ""),
            "ai_temperature": float(os.environ.get("AI_TEMPERATURE", "0.7")),
            "ai_max_tokens": int(os.environ.get("AI_MAX_TOKENS", "2000")),
            "ai_review_frequency": os.environ.get("AI_REVIEW_FREQUENCY", "block"),
            "ai_review_block_weeks": int(os.environ.get("AI_REVIEW_BLOCK_WEEKS", "6")),
            "admin_allowed_origins": ["http://localhost:5173", "http://localhost:8000"],
        }],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_sessions_expires_at'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_admin_audit_log_timestamp'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_table('model_pricing')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
